# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/xenial64"
    web01.vm.hostname = 'web01'
    web01.vm.box_url = "ubuntu/xenial64"

    web01.vm.network :private_network, ip: "192.168.55.101"

    web01.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web01"]
    end
  end
  
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/xenial64"
    web02.vm.hostname = 'web02'
    web02.vm.box_url = "ubuntu/xenial64"

    web02.vm.network :private_network, ip: "192.168.55.102"

    web02.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web02"]
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = 'db'
    db.vm.box_url = "ubuntu/xenial64"

    db.vm.network :private_network, ip: "192.168.55.103"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "db"]
    end
  end

  config.vm.define "manager" do |manager|
    manager.vm.box = "ubuntu/xenial64"
    manager.vm.hostname = 'manager'
    manager.vm.box_url = "ubuntu/xenial64"

    manager.vm.network :private_network, ip: "192.168.55.100"

    manager.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "manager"]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo swapoff -a
    sudo sh -c 'echo "192.168.55.100 manager" >> /etc/hosts'
    sudo sh -c 'echo "192.168.55.101 web01" >> /etc/hosts'
    sudo sh -c 'echo "192.168.55.102 web02" >> /etc/hosts'
    sudo sh -c 'echo "192.168.55.103 db" >> /etc/hosts'
    sudo sh -c 'echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf'
    sudo sh -c 'echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf'
    sudo sysctl --system    
  SHELL
  config.vm.provision "shell", path: 'docker.sh'
  config.vm.provision "shell", path: 'kubernetes.sh'
end  
